bike_trip = read.csv("C:/Users/amitai/Dropbox (Personal)/MBA/Business analysis/Project/bikeshare_trips_full.csv", header=TRUE, as.is=TRUE, na.strings=c("NA", ".", ""))
str(bike_trip)
summary(bike_trip)
colSums(is.na(bike_trip))
bike_trip$start_asdate = as.POSIXct(bike_trip$start_date, format = "%Y-%m-%d %H:%M:%S")
bike_trip$start_asdate = as.Date(bike_trip$start_asdate, format = "%Y-%m-%d")
bike_trip$end_asdate = as.POSIXct(bike_trip$end_date, format = "%Y-%m-%d %H:%M:%S")
bike_trip$end_asdate = as.Date(bike_trip$end_asdate, format = "%Y-%m-%d")
bike_trip$start_astime = as.POSIXct(bike_trip$start_date, format = "%Y-%m-%d %H:%M:%S")
bike_trip$start_astime = format(bike_trip$start_astime,"%H")
bike_trip$end_astime = as.POSIXct(bike_trip$end_date, format = "%Y-%m-%d %H:%M:%S")
bike_trip$end_astime = format(bike_trip$end_astime,"%H")
bike_trip$duration_min = bike_trip$duration_sec / 60
bike_trip$duration_min = round(bike_trip$duration_min, 2)
bike_trip$month_year = as.POSIXct(bike_trip$start_date, format = "%Y-%m-%d %H:%M:%S")
bike_trip$month_year = format(bike_trip$month_year,"%m-%Y")
str(bike_trip)
summary(bike_trip)
colSums(is.na(bike_trip))